resources:
- repo: self
  clean: true

pool:
  name: eas-demo-dev

steps:
- powershell: |
   Start-Process powershell -ArgumentList '.\scripts\build.ps1' -RedirectStandardOutput "stdout.txt" -RedirectStandardError "stderr.txt" -wait

   Get-Content -Path stdout.txt
   Get-Content -Path stderr.txt
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Build MovieDB Application'
  env:
    PUB_KEY:
    HAB_REVISION: 
    SIGNING_KEY:

- task: PowerShell@2
  displayName: 'Start Habitat Supervisor'
  inputs:
    targetType: filePath
    filePath: './scripts/hab_scheduled_task.ps1'
    arguments: '-runtask -origin "$(HAB_ORIGIN)" -password "$(SVC_ACC_PASSWORD)" -path "$(Build.SourcesDirectory)\results"'
    workingDirectory: '$(Build.SourcesDirectory)'
